#! /bin/bash
# Copyright (c) 2015  MRG-Info Bt.
# All rights reserved.
#
# Author: wavezone, 2015
#
# Please send feedback to wavezone@mrginfo.com
#
# /etc/init.d/motion
#
### BEGIN INIT INFO
# Provides:          motion
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Detecting motion
# Description:       Runs up the motion detection process
### END INIT INFO

DAEMON=/usr/local/PiCam/motion.py

test -f $DAEMON || exit 0

case "$1" in
    start)
        echo "Starting server"
        python3 $DAEMON start
        ;;
    stop)
        echo "Stopping server"
        # Stop the daemon
        python3 $DAEMON stop
        ;;
    restart)
        echo "Restarting server"
        python3 $DAEMON restart
        ;;
    *)
        echo "Usage: $DAEMON {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
